import Link from "next/link";
import { IconArrowLeft, IconCheck, IconMessage, IconPolygon, IconX } from "@tabler/icons-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { ReviewMapPreview } from "@/components/admin/review-map-preview";

export default async function ReviewLayerPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  return <main className="min-h-[100dvh] bg-surface-subtle pb-36"><header className="sticky top-0 z-10 flex min-h-16 items-center gap-3 border-b bg-surface px-4"><Button asChild variant="ghost" size="icon-sm"><Link href="/admin/layers" aria-label="Quay lại"><IconArrowLeft stroke={1.75}/></Link></Button><div className="min-w-0 flex-1"><h1 className="truncate text-sm font-semibold">Ranh giới phường, xã</h1><p className="text-xs text-muted-foreground">Review revision #19 · {id}</p></div><Badge>Chờ duyệt</Badge></header>
  <div className="mx-auto grid max-w-5xl gap-4 p-4 md:grid-cols-[1.25fr_0.75fr] md:p-6"><section className="overflow-hidden rounded-panel border bg-surface"><ReviewMapPreview/><div className="border-t p-4"><h2 className="font-semibold">Tóm tắt thay đổi</h2><div className="mt-4 grid grid-cols-3 gap-2 text-center"><div className="rounded-control bg-emerald-50 p-3"><strong className="block text-lg text-success">+2</strong><span className="text-xs text-muted-foreground">Thêm mới</span></div><div className="rounded-control bg-accent-subtle p-3"><strong className="block text-lg text-primary">3</strong><span className="text-xs text-muted-foreground">Chỉnh sửa</span></div><div className="rounded-control bg-red-50 p-3"><strong className="block text-lg text-destructive">−0</strong><span className="text-xs text-muted-foreground">Xóa</span></div></div></div></section>
  <aside className="space-y-4"><section className="rounded-panel border bg-surface p-4"><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-control bg-accent-subtle text-primary"><IconPolygon stroke={1.75}/></span><div><h2 className="text-sm font-semibold">Geometry hợp lệ</h2><p className="text-xs text-muted-foreground">Không tự cắt · diện tích dùng mét vuông</p></div></div><dl className="mt-4 divide-y text-sm"><div className="flex justify-between py-3"><dt className="text-muted-foreground">Người gửi</dt><dd className="font-medium">Nguyễn Văn An</dd></div><div className="flex justify-between py-3"><dt className="text-muted-foreground">Thời gian</dt><dd className="font-medium">21/08, 09:42</dd></div><div className="flex justify-between py-3"><dt className="text-muted-foreground">Revision nền</dt><dd className="font-medium">#18</dd></div></dl></section><section className="rounded-panel border bg-surface p-4"><h2 className="text-sm font-semibold">Bình luận</h2><textarea disabled title="Chưa kết nối endpoint bình luận review" className="mt-3 min-h-24 w-full resize-y rounded-control border bg-surface-subtle p-3 text-sm" placeholder="Ghi chú cho editor..."/><Button disabled title="Chưa kết nối endpoint bình luận review" variant="outline" className="mt-2 w-full"><IconMessage stroke={1.75}/>Thêm bình luận</Button></section></aside></div>
  <div className="fixed inset-x-0 bottom-16 z-20 border-t bg-surface p-3 md:bottom-0 md:left-60"><div className="mx-auto flex max-w-5xl gap-2"><Button disabled title="Chưa kết nối endpoint yêu cầu chỉnh sửa" variant="outline" className="flex-1 text-destructive"><IconX stroke={1.75}/>Yêu cầu chỉnh sửa</Button><Button disabled title="Chưa kết nối endpoint duyệt revision" className="flex-1"><IconCheck stroke={1.75}/>Duyệt thay đổi</Button></div></div></main>;
}
