import Link from "next/link";
import { IconDots, IconEdit, IconFileImport, IconPlus, IconSearch } from "@tabler/icons-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";

const layers = [
  { id: "wards", name: "Ranh giới phường, xã", type: "Polygon", count: "56", revision: "19", status: "Chờ duyệt", updated: "21/08/2026, 09:42" },
  { id: "offices", name: "Trụ sở hành chính", type: "Point", count: "94", revision: "18", status: "Đã xuất bản", updated: "20/08/2026, 16:10" },
  { id: "police", name: "Trụ sở công an", type: "Point", count: "67", revision: "12", status: "Bản nháp", updated: "19/08/2026, 14:05" },
  { id: "departments", name: "Sở, ban, ngành", type: "Mixed", count: "42", revision: "8", status: "Đã xuất bản", updated: "18/08/2026, 08:30" },
];

function Status({ value }: { value: string }) {
  const className = value === "Đã xuất bản" ? "bg-emerald-50 text-success" : value === "Chờ duyệt" ? "bg-amber-50 text-warning" : "bg-surface-subtle text-muted-foreground";
  return <Badge className={className}>{value}</Badge>;
}

export default function LayersPage() {
  return <main className="mx-auto max-w-[1440px] p-4 pb-24 sm:p-6 md:p-8"><header className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm text-muted-foreground">Dữ liệu bản đồ</p><h1 className="mt-1 text-2xl font-semibold tracking-[-0.02em]">Lớp dữ liệu</h1><p className="mt-2 text-sm text-muted-foreground">Tạo, biên tập và theo dõi vòng đời các lớp công bố.</p></div><div className="hidden gap-2 md:flex"><Button disabled title="Import wizard chưa kết nối API" variant="outline"><IconFileImport stroke={1.75} />Nhập dữ liệu</Button><Button disabled title="Schema builder chưa kết nối API"><IconPlus stroke={1.75} />Tạo lớp</Button></div></header>
  <section className="mt-7 rounded-panel border bg-surface"><div className="flex flex-wrap items-center gap-3 border-b p-4"><div className="relative min-w-[240px] flex-1"><IconSearch className="absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground" size={19} stroke={1.75}/><Input disabled title="Catalog query chưa kết nối API" className="pl-10" placeholder="Tìm tên hoặc mã lớp..." aria-label="Tìm lớp dữ liệu"/></div><select disabled title="Catalog query chưa kết nối API" className="h-11 rounded-control border bg-surface px-3 text-sm" aria-label="Lọc trạng thái"><option>Tất cả trạng thái</option><option>Đã xuất bản</option><option>Chờ duyệt</option><option>Bản nháp</option></select><select disabled title="Catalog query chưa kết nối API" className="h-11 rounded-control border bg-surface px-3 text-sm" aria-label="Lọc loại hình học"><option>Mọi loại geometry</option><option>Point</option><option>Polygon</option><option>Mixed</option></select></div>
  <div className="hidden overflow-x-auto md:block"><table className="w-full border-collapse text-left text-sm"><thead className="bg-surface-subtle text-xs text-muted-foreground"><tr><th className="px-5 py-3 font-medium">Tên lớp</th><th className="px-5 py-3 font-medium">Loại</th><th className="px-5 py-3 font-medium">Đối tượng</th><th className="px-5 py-3 font-medium">Revision</th><th className="px-5 py-3 font-medium">Trạng thái</th><th className="px-5 py-3 font-medium">Cập nhật</th><th className="w-24 px-5 py-3"><span className="sr-only">Thao tác</span></th></tr></thead><tbody className="divide-y">{layers.map((layer) => <tr key={layer.id} className="hover:bg-surface-subtle"><td className="px-5 py-4"><Link className="font-medium text-primary hover:underline" href={`/admin/layers/${layer.id}/edit`}>{layer.name}</Link><p className="mt-1 text-xs text-muted-foreground">danang:{layer.id}</p></td><td className="px-5 py-4">{layer.type}</td><td className="px-5 py-4">{layer.count}</td><td className="px-5 py-4">#{layer.revision}</td><td className="px-5 py-4"><Status value={layer.status}/></td><td className="whitespace-nowrap px-5 py-4 text-muted-foreground">{layer.updated}</td><td className="px-5 py-4"><div className="flex justify-end gap-1"><Button asChild variant="ghost" size="icon-sm"><Link href={`/admin/layers/${layer.id}/edit`} aria-label={`Biên tập ${layer.name}`}><IconEdit stroke={1.75}/></Link></Button><Button variant="ghost" size="icon-sm" aria-label={`Thêm thao tác cho ${layer.name}`}><IconDots stroke={1.75}/></Button></div></td></tr>)}</tbody></table></div>
  <div className="divide-y md:hidden">{layers.map((layer) => <article className="p-4" key={layer.id}><div className="flex items-start justify-between gap-3"><div><h2 className="font-medium">{layer.name}</h2><p className="mt-1 text-xs text-muted-foreground">{layer.type} · {layer.count} đối tượng · Revision #{layer.revision}</p></div><Status value={layer.status}/></div><div className="mt-4 flex items-center justify-between text-xs text-muted-foreground"><span>{layer.updated}</span><Button asChild variant="outline" size="sm"><Link href={`/admin/layers/${layer.id}/review`}>Xem / duyệt</Link></Button></div></article>)}</div>
  <footer className="flex items-center justify-between border-t px-5 py-4 text-sm text-muted-foreground"><span>4 lớp dữ liệu</span><span>Trang 1 / 1</span></footer></section></main>;
}
