const actions: Record<string, string> = {
  "auth.login_succeeded": "Đăng nhập thành công",
  "auth.logout": "Đăng xuất",
  "auth.password_verified": "Xác nhận mật khẩu",
  "auth.password_changed": "Đổi mật khẩu",
  "auth.password_reset_requested": "Yêu cầu đặt lại mật khẩu",
  "auth.password_reset_completed": "Đặt lại mật khẩu",
  "auth.sessions_revoked_all": "Đăng xuất trên mọi thiết bị",
  "auth.bootstrap_system_admin_created": "Tạo tài khoản quản trị đầu tiên",
  "auth.bootstrap_system_admin_failed": "Không thể tạo tài khoản quản trị đầu tiên",
  "auth.mfa_enrollment_started": "Bắt đầu thiết lập xác thực hai bước",
  "auth.mfa_enrollment_rotated": "Thiết lập lại ứng dụng xác thực",
  "auth.mfa_enrollment_confirmed": "Bật xác thực hai bước",
  "auth.mfa_recovery_codes_regenerated": "Tạo lại mã khôi phục",
  "user.created_manual": "Tạo tài khoản",
  "user.created_from_invite": "Kích hoạt tài khoản từ lời mời",
  "user.invited": "Gửi lời mời tạo tài khoản",
  "user.activated": "Kích hoạt tài khoản",
  "user.updated": "Cập nhật tài khoản",
  "user.mfa_reset": "Yêu cầu thiết lập lại xác thực hai bước",
  "user.password_reset_requested": "Gửi yêu cầu đặt lại mật khẩu",
  "user.session_revoked": "Đăng xuất một thiết bị",
  "user.sessions_revoked_all": "Đăng xuất tài khoản trên mọi thiết bị",
  "invite.created": "Gửi lời mời tạo tài khoản",
  "invite.accepted": "Chấp nhận lời mời",
  "invite.revoked": "Hủy lời mời",
  "invite.resend_requested": "Gửi lại lời mời",
  "user_import.applied": "Nhập danh sách tài khoản",
  "user_import.apply_rejected": "Không thể nhập danh sách tài khoản",
  "user_import.invite_created": "Tạo lời mời từ danh sách nhập",
  "layer.created": "Tạo lớp dữ liệu",
  "layer.updated": "Cập nhật lớp dữ liệu",
  "layer.reordered": "Sắp xếp lớp dữ liệu",
  "layer.archived": "Lưu trữ lớp dữ liệu",
  "layer.unarchived": "Đưa lớp trở lại danh sách",
  "layer_group.created": "Tạo nhóm lớp",
  "layer_group.updated": "Cập nhật nhóm lớp",
  "layer_group.reordered": "Sắp xếp nhóm lớp",
  "layer_group.archived": "Lưu trữ nhóm lớp",
  "revision.config_updated": "Cập nhật cấu hình phiên bản",
  "revision.successor_created": "Tạo bản nháp tiếp theo",
  "revision.submitted": "Gửi duyệt dữ liệu",
  "revision.approved": "Phê duyệt dữ liệu",
  "revision.changes_requested": "Yêu cầu chỉnh sửa dữ liệu",
  "revision.published": "Công bố dữ liệu",
  "publication.published": "Công bố dữ liệu",
  "publication.queued": "Tiếp nhận yêu cầu công bố",
  "publication.failed": "Công bố không thành công",
  "publication.rolled_back": "Khôi phục bản công bố trước",
  "feature.created": "Thêm đối tượng",
  "feature.updated": "Cập nhật đối tượng",
  "feature.deleted": "Xóa đối tượng",
  "feature.batch_synced": "Lưu các thay đổi đối tượng",
  "import.applied": "Nhập dữ liệu vào bản nháp",
  "attachment.scan_clean": "Tệp đã qua kiểm tra an toàn",
  "attachment.scan_rejected": "Tệp không đạt kiểm tra an toàn",
  "attachment.bound": "Thêm tệp đính kèm",
  "attachment.unbound": "Gỡ tệp đính kèm",
  "attachment.reordered": "Sắp xếp tệp đính kèm",
};

const resources: Record<string, string> = {
  user: "Tài khoản", auth: "Đăng nhập", session: "Thiết bị đăng nhập", admin_session: "Thiết bị đăng nhập",
  invite: "Lời mời", user_import: "Danh sách tài khoản", user_import_job: "Danh sách tài khoản",
  layer: "Lớp dữ liệu", layer_group: "Nhóm lớp", revision: "Phiên bản dữ liệu", layer_revision: "Phiên bản dữ liệu",
  feature: "Đối tượng bản đồ", import: "Nhập dữ liệu", import_job: "Nhập dữ liệu",
  publication: "Bản công bố", publication_snapshot: "Bản công bố", attachment: "Tệp đính kèm",
};

export function auditActionLabel(action: string) { return actions[action] ?? "Hoạt động hệ thống"; }
export function auditResourceLabel(resource: string) { return resources[resource] ?? "Hệ thống"; }
